FROM java:8
ARG CONSUMER_KEY
ARG CONSUMER_SECRET
ARG ACCESS_TOKEN
ARG TOKEN_SECRET

ENV CONSUMER_KEY=$CONSUMER_KEY
ENV CONSUMER_SECRET=$CONSUMER_SECRET
ENV ACCESS_TOKEN=$ACCESS_TOKEN
ENV TOKEN_SECRET=$TOKEN_SECRET

WORKDIR /app
ADD ./target/*jar-with-dependencies.jar app.jar
#CMD ["java" , "-jar" , "/app/app.jar"]